apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-users-api
  labels:
    app: udagram-users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram-users-api
  template:
    metadata:
      labels:
        app: udagram-users-api
    spec:
      containers:
      - name: udagram-users-api
        image: ifagacayaklar/udagram-users-api
        envFrom:
          - configMapRef:
              name: udagram-config
          - secretRef:
              name: udagram-secrets
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws/"
            readOnly: true
        ports:
        - containerPort: 8080
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret