apiVersion: v1
kind: Service
metadata:
  name: udagram-users-api
  labels:
    app: udagram-users-api
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: udagram-users-api
  type: ClusterIP

